CREATE FILE FORMAT IF NOT EXISTS {{bronze_db}}.{{schema}}.PARQUET_SCHEMA_EVOLUTION
  TYPE='PARQUET';

CREATE FILE FORMAT IF NOT EXISTS {{bronze_db}}.{{schema}}.CSV_SCHEMA_EVOLUTION
  TYPE='CSV'
  FIELD_DELIMITER=','
  PARSE_HEADER=true
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  ESCAPE_UNENCLOSED_FIELD = NONE
  ERROR_ON_COLUMN_COUNT_MISMATCH=false;